language: python
sudo: false
cache: pip
python:
  - 3.5
  - 3.8
env:
  - TOXENV=django22
  - TOXENV=quality
addons:
    apt:
        packages:
            - libblas-dev
            - liblapack-dev
            - gfortran
install:
  - pip install -r requirements/travis.txt
script:
    - make test
after_success:
    - coveralls
branches:
    only:
      - master
